"""Domain values for workspace-scoped repository guidance.

定义工作区范围仓库指引使用的领域值."""

from neuro_code.domain.workspace.instructions import (
    INSTRUCTION_FILENAME,
    MAX_DIRECTORY_DEPTH,
    MAX_INSTRUCTION_FILES,
    MAX_SINGLE_FILE_BYTES,
    MAX_TOTAL_BYTES,
    InstructionDiscoveryResult,
    InstructionFile,
    InstructionRejection,
    InstructionRejectionReason,
    compute_instruction_fingerprint,
    normalize_relative_path,
)
from neuro_code.domain.workspace.skills import (
    MAX_DESCRIPTION_LEN,
    MAX_FRONTMATTER_BYTES,
    MAX_NAME_LEN,
    MAX_SINGLE_SKILL_BYTES,
    MAX_SKILL_ANCESTOR_DEPTH,
    MAX_SKILL_ARGUMENT_BYTES,
    MAX_SKILL_CANDIDATES,
    MAX_SKILL_CATALOG_BYTES,
    MAX_SKILL_DIRECTORIES,
    MAX_SKILL_DIRECTORY_ENTRIES,
    MAX_SKILL_FILES,
    MAX_SKILL_SUBSTITUTIONS,
    MAX_SKILL_WALK_DEPTH,
    MAX_TOTAL_SKILL_BYTES,
    SKILL_CONFIG_DIRS,
    SKILL_FILENAME,
    SKILL_SUBDIR,
    ParsedFrontmatter,
    SkillDiscoveryResult,
    SkillInfo,
    SkillRejection,
    SkillRejectionReason,
    SkillScope,
    apply_skill_substitutions,
    compute_skill_fingerprint,
    extract_skill_body,
    is_valid_skill_name,
    normalize_skill_name,
    parse_frontmatter,
)
from neuro_code.domain.workspace.skills import (
    normalize_relative_path as normalize_skill_relative_path,
)

__all__ = [
    "INSTRUCTION_FILENAME",
    "MAX_DESCRIPTION_LEN",
    "MAX_DIRECTORY_DEPTH",
    "MAX_FRONTMATTER_BYTES",
    "MAX_INSTRUCTION_FILES",
    "MAX_NAME_LEN",
    "MAX_SINGLE_FILE_BYTES",
    "MAX_SINGLE_SKILL_BYTES",
    "MAX_SKILL_ANCESTOR_DEPTH",
    "MAX_SKILL_ARGUMENT_BYTES",
    "MAX_SKILL_CANDIDATES",
    "MAX_SKILL_CATALOG_BYTES",
    "MAX_SKILL_DIRECTORIES",
    "MAX_SKILL_DIRECTORY_ENTRIES",
    "MAX_SKILL_FILES",
    "MAX_SKILL_SUBSTITUTIONS",
    "MAX_SKILL_WALK_DEPTH",
    "MAX_TOTAL_BYTES",
    "MAX_TOTAL_SKILL_BYTES",
    "SKILL_CONFIG_DIRS",
    "SKILL_FILENAME",
    "SKILL_SUBDIR",
    "InstructionDiscoveryResult",
    "InstructionFile",
    "InstructionRejection",
    "InstructionRejectionReason",
    "ParsedFrontmatter",
    "SkillDiscoveryResult",
    "SkillInfo",
    "SkillRejection",
    "SkillRejectionReason",
    "SkillScope",
    "apply_skill_substitutions",
    "compute_instruction_fingerprint",
    "compute_skill_fingerprint",
    "extract_skill_body",
    "is_valid_skill_name",
    "normalize_relative_path",
    "normalize_skill_name",
    "normalize_skill_relative_path",
    "parse_frontmatter",
]
