"""Canonical application ports implemented by infrastructure adapters.

定义由基础设施适配器实现的规范应用端口."""

from neuro_code.application.ports.approval import PermissionApprover
from neuro_code.application.ports.background_tasks import (
    BackgroundTaskManager,
    BackgroundTaskSupervisor,
)
from neuro_code.application.ports.client_filesystem import ClientFileSystem
from neuro_code.application.ports.client_terminal import ClientTerminal, ClientTerminalResult
from neuro_code.application.ports.http import HttpClientPolicy
from neuro_code.application.ports.model import ModelProvider, ModelToolPolicy
from neuro_code.application.ports.provider_catalog import (
    ProviderCatalog,
    ProviderCatalogError,
    ProviderCatalogResult,
    ProviderConnectionSpec,
)
from neuro_code.application.ports.provider_settings import (
    ManagedProviderProfile,
    ManagedProviderSettings,
    ManagedProxyPolicy,
    ProviderSettingsStore,
)
from neuro_code.application.ports.sandbox import (
    LocalProcessCancellationPolicy,
    LocalProcessEnvironmentPolicy,
    LocalProcessFilesystemPolicy,
    LocalProcessLifecycle,
    LocalProcessLifecycleCapability,
    LocalProcessNetworkPolicy,
    LocalProcessPurpose,
    LocalProcessSandbox,
    LocalProcessStdioMode,
    LocalWorkspaceAccess,
    LocalWorkspaceAccessMode,
    OwnedLocalProcess,
    SandboxedProcessRequest,
    lifecycle_capability_satisfies,
)
from neuro_code.application.ports.storage import SessionStore
from neuro_code.application.ports.terminal import (
    InteractiveTerminalManager,
    InteractiveTerminalSession,
)
from neuro_code.application.ports.tools import (
    MAX_TOOL_OUTPUT_ARTIFACT_BYTES,
    MAX_TOOL_OUTPUT_ARTIFACT_READ_BYTES,
    TOOL_OUTPUT_ARTIFACT_PRUNE_GRACE_SECONDS,
    InteractionControlTool,
    Tool,
    ToolCollection,
    ToolContext,
    ToolOutputArtifact,
    ToolOutputArtifactGarbageCollector,
    ToolOutputArtifactPruneResult,
    ToolOutputArtifactRead,
    ToolOutputArtifactReader,
    ToolOutputArtifactStore,
)
from neuro_code.application.ports.ui_preferences import UiPreferencesStore
from neuro_code.application.ports.user_interaction import (
    InteractionEventSink,
    InteractionUnavailable,
    UnavailableUserInteraction,
    UserInputOption,
    UserInputRequest,
    UserInputResponse,
    UserInteractionPort,
)
from neuro_code.application.ports.workspace import WorkspaceIdentity, WorkspacePathResolver
from neuro_code.application.ports.workspace_changes import (
    WorkspaceChangeCheckpoint,
    WorkspaceChangeEventPayload,
    WorkspaceChangeFileEventPayload,
    WorkspaceChangeHiddenFileEventPayload,
    WorkspaceChangeHiddenReason,
    WorkspaceChangeJournal,
    WorkspaceChangeObserver,
    WorkspaceChangeReport,
    WorkspaceChangeStatus,
    WorkspaceChangeVisibleFileEventPayload,
    WorkspaceDiffFile,
    WorkspaceDiffMove,
    WorkspaceDiffResult,
    WorkspaceFileChange,
    WorkspaceMutationJournalProjection,
    WorkspaceMutationTargetProvider,
)

__all__ = [
    "MAX_TOOL_OUTPUT_ARTIFACT_BYTES",
    "MAX_TOOL_OUTPUT_ARTIFACT_READ_BYTES",
    "TOOL_OUTPUT_ARTIFACT_PRUNE_GRACE_SECONDS",
    "BackgroundTaskManager",
    "BackgroundTaskSupervisor",
    "ClientFileSystem",
    "ClientTerminal",
    "ClientTerminalResult",
    "HttpClientPolicy",
    "InteractionControlTool",
    "InteractionEventSink",
    "InteractionUnavailable",
    "InteractiveTerminalManager",
    "InteractiveTerminalSession",
    "LocalProcessCancellationPolicy",
    "LocalProcessEnvironmentPolicy",
    "LocalProcessFilesystemPolicy",
    "LocalProcessLifecycle",
    "LocalProcessLifecycleCapability",
    "LocalProcessNetworkPolicy",
    "LocalProcessPurpose",
    "LocalProcessSandbox",
    "LocalProcessStdioMode",
    "LocalWorkspaceAccess",
    "LocalWorkspaceAccessMode",
    "ManagedProviderProfile",
    "ManagedProviderSettings",
    "ManagedProxyPolicy",
    "ModelProvider",
    "ModelToolPolicy",
    "OwnedLocalProcess",
    "PermissionApprover",
    "ProviderCatalog",
    "ProviderCatalogError",
    "ProviderCatalogResult",
    "ProviderConnectionSpec",
    "ProviderSettingsStore",
    "SandboxedProcessRequest",
    "SessionStore",
    "Tool",
    "ToolCollection",
    "ToolContext",
    "ToolOutputArtifact",
    "ToolOutputArtifactGarbageCollector",
    "ToolOutputArtifactPruneResult",
    "ToolOutputArtifactRead",
    "ToolOutputArtifactReader",
    "ToolOutputArtifactStore",
    "UiPreferencesStore",
    "UnavailableUserInteraction",
    "UserInputOption",
    "UserInputRequest",
    "UserInputResponse",
    "UserInteractionPort",
    "WorkspaceChangeCheckpoint",
    "WorkspaceChangeEventPayload",
    "WorkspaceChangeFileEventPayload",
    "WorkspaceChangeHiddenFileEventPayload",
    "WorkspaceChangeHiddenReason",
    "WorkspaceChangeJournal",
    "WorkspaceChangeObserver",
    "WorkspaceChangeReport",
    "WorkspaceChangeStatus",
    "WorkspaceChangeVisibleFileEventPayload",
    "WorkspaceDiffFile",
    "WorkspaceDiffMove",
    "WorkspaceDiffResult",
    "WorkspaceFileChange",
    "WorkspaceIdentity",
    "WorkspaceMutationJournalProjection",
    "WorkspaceMutationTargetProvider",
    "WorkspacePathResolver",
    "lifecycle_capability_satisfies",
]
