"""Provider-independent domain contracts.

与 Provider 无关的领域契约."""

from neuro_code.domain.background_tasks.models import (
    DEFAULT_BACKGROUND_WAKE_COOLDOWN_SECONDS,
    DEFAULT_BACKGROUND_WAKE_MAX_PER_SESSION,
    MAX_BACKGROUND_TASK_WAIT_IDS,
    MAX_BACKGROUND_WAKE_COUNT,
    MAX_BACKGROUND_WAKE_TASK_IDS,
    BackgroundTaskKillOutcome,
    BackgroundTaskKillResult,
    BackgroundTaskSnapshot,
    BackgroundTaskStatus,
    BackgroundTaskWaitMode,
    BackgroundTaskWaitResult,
    BackgroundTaskWakePolicy,
    BackgroundWakeDecision,
    BackgroundWakeLimits,
    BackgroundWakeState,
)
from neuro_code.domain.conversation.compaction import (
    COMPACTION_SOURCE_FINGERPRINT_BYTES,
    MAX_DURABLE_COMPACTION_ID_BYTES,
    MAX_DURABLE_COMPACTION_SUMMARY_BYTES,
    DurableCompactionItem,
    compute_compaction_source_fingerprint,
)
from neuro_code.domain.conversation.context import (
    ModelContext,
    estimate_context_tokens,
    estimate_text_tokens,
)
from neuro_code.domain.conversation.events import (
    AgentEvent,
    AgentEventKind,
    ModelBackendToolCompleted,
    ModelBackendToolStarted,
    ModelCompleted,
    ModelEvent,
    ModelInputTokenSemantics,
    ModelProviderAttemptFailed,
    ModelProviderSelected,
    ModelReasoningDelta,
    ModelTextDelta,
    ModelToolCall,
    ModelUsage,
)
from neuro_code.domain.conversation.interaction_mode import (
    InteractionMode,
    interaction_mode_guidance,
)
from neuro_code.domain.conversation.messages import (
    AUDIO_MODEL_PLACEHOLDER,
    BLOB_MODEL_PLACEHOLDER,
    ContentPart,
    ContentPartKind,
    ContextItemKind,
    Message,
    PreservedContextItem,
    Role,
    SessionItem,
    ToolCall,
)
from neuro_code.domain.conversation.reasoning import ReasoningEffort, reasoning_guidance
from neuro_code.domain.conversation.request import (
    MAX_REQUEST_SNAPSHOT_ID_BYTES,
    REQUEST_SNAPSHOT_SCHEMA_VERSION,
    ModelRequestSnapshot,
    RequestContextFingerprints,
    context_fingerprints,
)
from neuro_code.domain.plans import (
    MAX_PLAN_COMMENT_BYTES,
    MAX_PLAN_COMMENT_ID_BYTES,
    MAX_PLAN_COMMENTS,
    PlanComment,
    PlanStep,
    PlanStepStatus,
    SessionPlan,
)
from neuro_code.domain.session_tasks import (
    MAX_QUEUED_SESSION_TASKS,
    MAX_SESSION_TASK_ID_BYTES,
    SessionTask,
    SessionTaskKind,
    SessionTaskStatus,
)
from neuro_code.domain.sessions import SessionSnapshot, SessionSummary
from neuro_code.domain.sessions.search import SessionSearchHit, SessionSearchPage
from neuro_code.domain.terminal.models import (
    MAX_TERMINAL_DIMENSION,
    MAX_TERMINAL_OUTPUT_BYTES,
    MAX_TERMINAL_READ_BYTES,
    MAX_TERMINAL_WRITE_BYTES,
    TerminalOutputChunk,
    TerminalSignal,
    TerminalSize,
)
from neuro_code.domain.tools import (
    ToolDefinition,
    ToolExecutionMode,
    ToolExecutionResult,
    ToolResult,
)
from neuro_code.shared.ui_language import UiLanguage

__all__ = [
    "AUDIO_MODEL_PLACEHOLDER",
    "BLOB_MODEL_PLACEHOLDER",
    "COMPACTION_SOURCE_FINGERPRINT_BYTES",
    "DEFAULT_BACKGROUND_WAKE_COOLDOWN_SECONDS",
    "DEFAULT_BACKGROUND_WAKE_MAX_PER_SESSION",
    "MAX_BACKGROUND_TASK_WAIT_IDS",
    "MAX_BACKGROUND_WAKE_COUNT",
    "MAX_BACKGROUND_WAKE_TASK_IDS",
    "MAX_DURABLE_COMPACTION_ID_BYTES",
    "MAX_DURABLE_COMPACTION_SUMMARY_BYTES",
    "MAX_PLAN_COMMENTS",
    "MAX_PLAN_COMMENT_BYTES",
    "MAX_PLAN_COMMENT_ID_BYTES",
    "MAX_QUEUED_SESSION_TASKS",
    "MAX_REQUEST_SNAPSHOT_ID_BYTES",
    "MAX_SESSION_TASK_ID_BYTES",
    "MAX_TERMINAL_DIMENSION",
    "MAX_TERMINAL_OUTPUT_BYTES",
    "MAX_TERMINAL_READ_BYTES",
    "MAX_TERMINAL_WRITE_BYTES",
    "REQUEST_SNAPSHOT_SCHEMA_VERSION",
    "AgentEvent",
    "AgentEventKind",
    "BackgroundTaskKillOutcome",
    "BackgroundTaskKillResult",
    "BackgroundTaskSnapshot",
    "BackgroundTaskStatus",
    "BackgroundTaskWaitMode",
    "BackgroundTaskWaitResult",
    "BackgroundTaskWakePolicy",
    "BackgroundWakeDecision",
    "BackgroundWakeLimits",
    "BackgroundWakeState",
    "ContentPart",
    "ContentPartKind",
    "ContextItemKind",
    "DurableCompactionItem",
    "InteractionMode",
    "Message",
    "ModelBackendToolCompleted",
    "ModelBackendToolStarted",
    "ModelCompleted",
    "ModelContext",
    "ModelEvent",
    "ModelInputTokenSemantics",
    "ModelProviderAttemptFailed",
    "ModelProviderSelected",
    "ModelReasoningDelta",
    "ModelRequestSnapshot",
    "ModelTextDelta",
    "ModelToolCall",
    "ModelUsage",
    "PlanComment",
    "PlanStep",
    "PlanStepStatus",
    "PreservedContextItem",
    "ReasoningEffort",
    "RequestContextFingerprints",
    "Role",
    "SessionItem",
    "SessionPlan",
    "SessionSearchHit",
    "SessionSearchPage",
    "SessionSnapshot",
    "SessionSummary",
    "SessionTask",
    "SessionTaskKind",
    "SessionTaskStatus",
    "TerminalOutputChunk",
    "TerminalSignal",
    "TerminalSize",
    "ToolCall",
    "ToolDefinition",
    "ToolExecutionMode",
    "ToolExecutionResult",
    "ToolResult",
    "UiLanguage",
    "compute_compaction_source_fingerprint",
    "context_fingerprints",
    "estimate_context_tokens",
    "estimate_text_tokens",
    "interaction_mode_guidance",
    "reasoning_guidance",
]
