"""Provider-independent domain contracts."""

from neuro_code.domain.background_tasks import (
    DEFAULT_BACKGROUND_WAKE_COOLDOWN_SECONDS,
    DEFAULT_BACKGROUND_WAKE_MAX_PER_SESSION,
    MAX_BACKGROUND_TASK_WAIT_IDS,
    MAX_BACKGROUND_WAKE_COUNT,
    MAX_BACKGROUND_WAKE_TASK_IDS,
    BackgroundTaskKillOutcome,
    BackgroundTaskKillResult,
    BackgroundTaskSnapshot,
    BackgroundTaskStatus,
    BackgroundTaskWaitMode,
    BackgroundTaskWaitResult,
    BackgroundTaskWakePolicy,
    BackgroundWakeDecision,
    BackgroundWakeLimits,
    BackgroundWakeState,
)
from neuro_code.domain.context_usage import estimate_context_tokens, estimate_text_tokens
from neuro_code.domain.events import AgentEvent, AgentEventKind
from neuro_code.domain.interaction_mode import InteractionMode, interaction_mode_guidance
from neuro_code.domain.messages import (
    ContentPart,
    ContentPartKind,
    ContextItemKind,
    Message,
    PreservedContextItem,
    Role,
    SessionItem,
    ToolCall,
)
from neuro_code.domain.model_context import ModelContext
from neuro_code.domain.model_events import (
    ModelBackendToolCompleted,
    ModelBackendToolStarted,
    ModelCompleted,
    ModelEvent,
    ModelProviderAttemptFailed,
    ModelProviderSelected,
    ModelReasoningDelta,
    ModelTextDelta,
    ModelToolCall,
)
from neuro_code.domain.plans import (
    MAX_PLAN_COMMENT_BYTES,
    MAX_PLAN_COMMENT_ID_BYTES,
    MAX_PLAN_COMMENTS,
    PlanComment,
    PlanStep,
    PlanStepStatus,
    SessionPlan,
)
from neuro_code.domain.reasoning import ReasoningEffort, reasoning_guidance
from neuro_code.domain.session_search import SessionSearchHit, SessionSearchPage
from neuro_code.domain.session_tasks import (
    MAX_QUEUED_SESSION_TASKS,
    MAX_SESSION_TASK_ID_BYTES,
    SessionTask,
    SessionTaskKind,
    SessionTaskStatus,
)
from neuro_code.domain.sessions import SessionSnapshot, SessionSummary
from neuro_code.domain.terminal import (
    MAX_TERMINAL_DIMENSION,
    MAX_TERMINAL_OUTPUT_BYTES,
    MAX_TERMINAL_READ_BYTES,
    MAX_TERMINAL_WRITE_BYTES,
    TerminalOutputChunk,
    TerminalSignal,
    TerminalSize,
)
from neuro_code.domain.tools import ToolDefinition, ToolResult
from neuro_code.domain.ui_preferences import UiLanguage

__all__ = [
    "DEFAULT_BACKGROUND_WAKE_COOLDOWN_SECONDS",
    "DEFAULT_BACKGROUND_WAKE_MAX_PER_SESSION",
    "MAX_BACKGROUND_TASK_WAIT_IDS",
    "MAX_BACKGROUND_WAKE_COUNT",
    "MAX_BACKGROUND_WAKE_TASK_IDS",
    "MAX_PLAN_COMMENTS",
    "MAX_PLAN_COMMENT_BYTES",
    "MAX_PLAN_COMMENT_ID_BYTES",
    "MAX_QUEUED_SESSION_TASKS",
    "MAX_SESSION_TASK_ID_BYTES",
    "MAX_TERMINAL_DIMENSION",
    "MAX_TERMINAL_OUTPUT_BYTES",
    "MAX_TERMINAL_READ_BYTES",
    "MAX_TERMINAL_WRITE_BYTES",
    "AgentEvent",
    "AgentEventKind",
    "BackgroundTaskKillOutcome",
    "BackgroundTaskKillResult",
    "BackgroundTaskSnapshot",
    "BackgroundTaskStatus",
    "BackgroundTaskWaitMode",
    "BackgroundTaskWaitResult",
    "BackgroundTaskWakePolicy",
    "BackgroundWakeDecision",
    "BackgroundWakeLimits",
    "BackgroundWakeState",
    "ContentPart",
    "ContentPartKind",
    "ContextItemKind",
    "InteractionMode",
    "Message",
    "ModelBackendToolCompleted",
    "ModelBackendToolStarted",
    "ModelCompleted",
    "ModelContext",
    "ModelEvent",
    "ModelProviderAttemptFailed",
    "ModelProviderSelected",
    "ModelReasoningDelta",
    "ModelTextDelta",
    "ModelToolCall",
    "PlanComment",
    "PlanStep",
    "PlanStepStatus",
    "PreservedContextItem",
    "ReasoningEffort",
    "Role",
    "SessionItem",
    "SessionPlan",
    "SessionSearchHit",
    "SessionSearchPage",
    "SessionSnapshot",
    "SessionSummary",
    "SessionTask",
    "SessionTaskKind",
    "SessionTaskStatus",
    "TerminalOutputChunk",
    "TerminalSignal",
    "TerminalSize",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "UiLanguage",
    "estimate_context_tokens",
    "estimate_text_tokens",
    "interaction_mode_guidance",
    "reasoning_guidance",
]
