# ruff: noqa: RUF001
from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from neuro_code.domain.ui_preferences import UiLanguage

# Natural Chinese interface copy deliberately uses full-width punctuation.

_ENGLISH: Final[dict[str, str]] = {
    "subtitle": "Terminal coding agent",
    "prompt.placeholder": "Ask Neuro Code... (/help for commands)",
    "shortcuts": "^C Cancel  ^Q Quit  Shift+Tab Mode  ^P Model  ^E Effort  ^R Sessions  ^, Settings  ^L Clear",
    "label.error": "Error",
    "label.status": "Status",
    "label.tool": "Tool",
    "approval.title": "Tool approval required",
    "approval.tool": "Tool: {tool}",
    "approval.policy": "Policy: {policy}",
    "approval.allow_once": "Allow once [A]",
    "approval.allow_session": "Allow identical action this session [S]",
    "approval.unscoped": "Session approval is unavailable for an action that cannot be scoped safely.",
    "approval.deny": "Deny [D/Esc/Ctrl+C]",
    "provider.title": "Select provider profile",
    "provider.help": "Switching profile starts a new conversation. Esc/Ctrl+C closes this picker.",
    "marker.current": "current",
    "marker.default": "default",
    "marker.unavailable": "unavailable",
    "marker.credential_missing": "credential missing",
    "session.search": "Session search: {query}",
    "session.title": "Workspace sessions",
    "session.help": "Only sessions from this workspace are listed. Filter with /sessions QUERY. Esc/Ctrl+C closes this picker.",
    "session.resume_via": "resume via {profile}",
    "session.legacy_sandbox": "legacy sandbox",
    "session.sandbox": "sandbox {profile}",
    "session.restart_required": "restart required",
    "settings.title": "Settings",
    "settings.description": "Interface language",
    "settings.current": "current",
    "settings.help": "The choice applies immediately and is saved for future TUI launches.",
    "effort.title": "Reasoning effort",
    "effort.description.low": "Fastest; direct answers and minimal required checks",
    "effort.description.medium": "Balanced speed, routine inspection, and focused checks",
    "effort.description.high": "Deeper review and proactive verification (default)",
    "effort.description.xhigh": "Hard tasks, edge cases, and multiple validation passes",
    "effort.description.ultracode": "xhigh policy plus future workflow orchestration",
    "effort.workflow_planned": "workflow planned; xhigh policy today",
    "effort.help": "The selected level controls Neuro Code's review policy from the next model step. Native provider effort controls remain capability-gated; Ultracode currently falls back to xhigh without starting sub-agent workflows.",
    "runtime.model": "MODEL",
    "runtime.context": "CTX",
    "runtime.context_unknown": "?",
    "runtime.context_help_unknown": "The provider context window is not configured, so a percentage cannot be calculated.",
    "runtime.context_help_estimated": "Estimated conversation context: approximately {used} / {window} tokens. Provider-reported usage replaces this estimate after a model step.",
    "runtime.context_help_reported": "Conversation context after the latest model step: {used} / {window} provider-reported tokens.",
    "runtime.effort": "EFFORT",
    "runtime.effort_help": "Application review policy. Ultracode falls back to xhigh until workflow orchestration is implemented.",
    "runtime.workspace": "CWD",
    "runtime.mode": "MODE",
    "runtime.mode_help.normal": "Normal: read-only tools run automatically; edits and commands require approval.",
    "runtime.mode_help.accept-edits": "Accept Edits: reads and workspace edits run automatically; commands and other effects still require approval.",
    "runtime.mode_help.plan": "Plan: only read-only exploration is allowed; side-effecting requests are denied.",
    "runtime.mode_help.auto": "Auto (limited): reads and edits run automatically; commands and network effects still require approval until a safety classifier is implemented.",
    "runtime.mode_help_auto_unrestricted": "Auto was explicitly authorized by --always-approve. Explicit deny rules and the configured process sandbox still apply; no safety classifier is active yet.",
    "startup.resumed": "Resumed session {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "Ready · {provider}/{model} · {cwd}",
    "turn.running": "A turn is already running.",
    "turn.waiting": "Thinking...",
    "turn.no_response": "(no text response)",
    "turn.cancelled": "Turn cancelled.",
    "turn.reasoning": "Reasoning...",
    "turn.thinking_completed": "Thought for {duration} · model step {step}",
    "turn.completed": "Turn completed in {duration} · {steps} model step(s)",
    "turn.cancel_requested": "Cancellation requested.",
    "turn.draft_cleared": "Draft cleared.",
    "turn.none_running": "No turn is running.",
    "provider.failed": "Provider {provider} failed before output: {message}",
    "provider.selected": "Provider {provider}/{model} selected.",
    "provider.fallback_selected": "Provider {provider}/{model} fallback selected.",
    "tool.hosted_started": "● Hosted {name}",
    "tool.hosted_completed": "└ Completed {name} in {duration}",
    "tool.requested": "● {invocation}",
    "tool.permission_allowed": "├ Allowed · {policy}",
    "tool.permission_denied": "└ Permission denied for {name}: {reason}",
    "tool.awaiting_approval": "├ Waiting for approval · {name}",
    "tool.approval_resolved": "├ Approval {outcome} · {name}",
    "tool.completed": "└ Completed {name} in {duration}",
    "tool.failed": "└ Failed {name} in {duration}: {message}",
    "tool.card.hosted": "Hosted",
    "tool.card.allowed": "Allowed · {reason}",
    "tool.card.approval_required": "Approval required · {reason}",
    "tool.card.awaiting_approval": "Waiting for approval",
    "tool.card.approval": "Approval · {outcome}",
    "tool.card.running": "Running",
    "tool.card.output": "Output · {lines} line(s)",
    "tool.card.output_empty": "Output · no output",
    "tool.card.error": "Error output · {lines} line(s)",
    "tool.card.error_empty": "Error output · no details",
    "tool.card.lines_omitted": "... {count} middle line(s) omitted",
    "tool.card.preview_truncated": "... preview truncated at the display limit",
    "tool.card.diff_truncated": "... diff truncated at the display limit",
    "tool.card.details_expanded": "▾ Details shown · click or press Enter to collapse",
    "tool.card.details_collapsed": "▸ Details hidden · click or press Enter to expand",
    "tool.card.files_omitted": "... {count} changed file(s) omitted",
    "tool.card.scan_limited": "Workspace change scan reached its safety limit",
    "tool.card.change.created": "Created {path} (+{additions})",
    "tool.card.change.modified": "Edited {path} (+{additions} -{deletions})",
    "tool.card.change.deleted": "Deleted {path} (-{deletions})",
    "tool.card.hidden.sensitive": "Change contents hidden for a sensitive file",
    "tool.card.hidden.large": "Change contents hidden because the file is too large",
    "tool.card.hidden.budget": "Change contents hidden because the scan budget was reached",
    "tool.card.hidden.binary": "Binary change; text diff unavailable",
    "tool.card.hidden.redacted": "Changed credential values were redacted",
    "tool.card.hidden.unavailable": "Change contents are unavailable",
    "tool.card.completed": "Completed · {duration}",
    "tool.card.failed": "Failed · {duration}",
    "tool.card.denied": "Denied · {reason}",
    "tool.approval.allow_once": "allowed once",
    "tool.approval.allow_session": "allowed for this session",
    "tool.approval.deny": "denied",
    "tool.approval.unknown": "resolved",
    "value.unknown": "unknown",
    "command_hint.tab": "Tab complete",
    "command.tasks_arguments": "/tasks does not accept arguments.",
    "command.arguments": "/{command} does not accept arguments.",
    "command.help": "Commands: /help, /status, /mode [MODE], /settings (alias /setting), /provider [PROFILE] (alias /model), /effort [LEVEL] (alias /reasoning), /sessions [QUERY], /resume [SESSION_ID], /rename TITLE (alias /title), /tasks, /cancel, /clear, /quit (alias /exit).",
    "command.status": "Provider: {provider}/{model} · Context: {context} · Effort: {effort} · Mode: {mode} · Session: {session}{profile} · CWD: {cwd}",
    "command.not_created": "not created",
    "command.profile": " · Profile: {profile}",
    "command.unknown": "Unknown command: /{command}. Use /help.",
    "transcript.cleared": "Transcript cleared.",
    "provider.switch_unavailable": "Provider switching is unavailable.",
    "provider.switch_running": "Cannot switch provider while a turn is running.",
    "effort.unavailable": "Reasoning-effort control is unavailable.",
    "effort.switch_running": "Cannot change reasoning effort while a turn is running.",
    "effort.invalid": "Unknown effort {value!r}. Choose one of: {levels}.",
    "effort.already_selected": "Reasoning effort is already {glyph} {effort}.",
    "effort.changed": "Reasoning effort changed to {glyph} {effort}; it applies from the next model step.",
    "effort.changed_fallback": "Ultracode selected; workflow orchestration is not implemented yet, so the {effective} review policy applies without sub-agent workflows.",
    "effort.save_failed": "The effort changed for this run, but the preference could not be saved: {error}",
    "mode.current": "Current mode: {mode}. Available modes: {modes}.",
    "mode.invalid": "Unknown mode {value!r}. Choose one of: {modes}.",
    "mode.unavailable": "Interaction-mode control is unavailable.",
    "mode.switch_running": "Cannot change mode while a turn is running.",
    "mode.already_selected": "Interaction mode is already {glyph} {mode}.",
    "mode.changed": "Interaction mode changed to {glyph} {mode}.",
    "mode.changed_auto_limited": "Auto mode selected in its safe preview: reads and edits are automatic, while commands and network effects still require approval. The safety classifier is not implemented yet.",
    "mode.save_failed": "The mode changed for this run, but the preference could not be saved: {error}",
    "mode.limited": "limited",
    "provider.already_selected": "Provider profile {profile} is already selected.",
    "provider.switched": "Provider profile switched to {profile} ({provider}/{model}).{stopped}",
    "provider.switched_saved": "Provider profile switched to {profile} ({provider}/{model}). The previous session {session_id} remains saved; the next prompt starts a new conversation.{stopped}",
    "tasks.stopped_one": " Stopped 1 background task from the previous session.",
    "tasks.stopped_many": " Stopped {count} background tasks from the previous session.",
    "session.resume_unavailable": "Interactive session resume is unavailable.",
    "session.resume_running": "Cannot resume a session while a turn is running.",
    "session.none": "No sessions found for this workspace.",
    "session.none_matching": "No sessions found for this workspace matching {query!r}.",
    "session.rename_unavailable": "Interactive session rename is unavailable.",
    "session.rename_running": "Cannot rename a session while a turn is running.",
    "session.renamed": "Session {session_id} renamed to {title!r}.",
    "session.already_open": "Session {session_id} is already open.",
    "session.profile": "profile {profile}",
    "session.profile_unavailable": "profile {profile}; source profile {source} is not ready locally",
    "session.previous_saved": " Previous session {session_id} remains saved.",
    "session.resumed": "Resumed session {session_id} with {profile_note} ({provider}/{model}).{previous}{stopped}",
    "tasks.unavailable": "Background task visibility is unavailable.",
    "tasks.none": "No background tasks for the current session.",
    "tasks.heading": "Background tasks:\n{lines}",
    "tasks.omitted": "... {count} older task(s) omitted",
    "tasks.summary": "{task_id} · {status}{exit_note} · {bytes} output bytes{truncated} · started {started}",
    "tasks.exit": " · exit {code}",
    "tasks.truncated": " (preview truncated)",
    "tasks.status.running": "running",
    "tasks.status.completed": "completed",
    "tasks.status.failed": "failed",
    "tasks.status.timed_out": "timed out",
    "tasks.status.cancelled": "cancelled",
    "tasks.completion.completed": "Background task {task_id} completed{exit_note}.",
    "tasks.completion.failed": "Background task {task_id} failed{exit_note}.",
    "tasks.completion.timed_out": "Background task {task_id} timed out{exit_note}.",
    "tasks.completion.cancelled": "Background task {task_id} was cancelled{exit_note}.",
    "tasks.completion.exit": " (exit {code})",
    "restore.result": "Restored result for {name}.",
    "restore.request": "Restored tool request: {names}.",
    "restore.truncated": "... [restored message truncated]",
    "settings.changed": "Interface language changed to {language}.",
    "settings.save_failed": "The language changed for this session, but the preference could not be saved: {error}",
}

_CHINESE: Final[dict[str, str]] = {
    "subtitle": "终端编程智能体",
    "prompt.placeholder": "询问 Neuro Code……（输入 /help 查看命令）",
    "shortcuts": "^C 取消  ^Q 退出  Shift+Tab 模式  ^P 模型  ^E 强度  ^R 会话  ^, 设置  ^L 清屏",
    "label.error": "错误",
    "label.status": "状态",
    "label.tool": "工具",
    "approval.title": "需要工具授权",
    "approval.tool": "工具：{tool}",
    "approval.policy": "策略：{policy}",
    "approval.allow_once": "仅允许本次 [A]",
    "approval.allow_session": "本会话允许相同操作 [S]",
    "approval.unscoped": "该操作无法安全限定范围，因此不能授予会话级权限。",
    "approval.deny": "拒绝 [D/Esc/Ctrl+C]",
    "provider.title": "选择供应商配置",
    "provider.help": "切换配置会开始新对话。按 Esc/Ctrl+C 关闭选择器。",
    "marker.current": "当前",
    "marker.default": "默认",
    "marker.unavailable": "不可用",
    "marker.credential_missing": "缺少凭据",
    "session.search": "会话搜索：{query}",
    "session.title": "当前工作区会话",
    "session.help": "仅列出当前工作区的会话。使用 /sessions 查询词筛选；按 Esc/Ctrl+C 关闭。",
    "session.resume_via": "通过 {profile} 恢复",
    "session.legacy_sandbox": "旧版沙箱",
    "session.sandbox": "沙箱 {profile}",
    "session.restart_required": "需要重启",
    "settings.title": "设置",
    "settings.description": "界面语言",
    "settings.current": "当前",
    "settings.help": "选择会立即生效，并用于以后启动的 TUI。",
    "effort.title": "思考强度",
    "effort.description.low": "最快；直接回答并仅执行必要检查",
    "effort.description.medium": "平衡速度、常规检查和针对性验证",
    "effort.description.high": "更深入地审查并主动验证（默认）",
    "effort.description.xhigh": "面向困难任务、边界情况和多轮验证",
    "effort.description.ultracode": "xhigh 策略加后续工作流编排",
    "effort.workflow_planned": "工作流待开发；当前使用 xhigh 策略",
    "effort.help": "所选等级从下一次模型步骤开始控制 Neuro Code 的审查策略。供应商原生强度控制仍按能力启用；Ultracode 当前只回退到 xhigh，不会启动尚未实现的子代理工作流。",
    "runtime.model": "模型",
    "runtime.context": "上下文",
    "runtime.context_unknown": "未知",
    "runtime.context_help_unknown": "当前供应商没有配置上下文窗口，因此无法计算占用百分比。",
    "runtime.context_help_estimated": "当前对话上下文估算约为 {used} / {window} token；模型步骤返回用量后会改用供应商数据。",
    "runtime.context_help_reported": "最近模型步骤后的对话上下文为 {used} / {window} 个供应商报告的 token。",
    "runtime.effort": "强度",
    "runtime.effort_help": "这是应用层审查策略。工作流编排实现前，Ultracode 会回退到 xhigh。",
    "runtime.workspace": "工作区",
    "runtime.mode": "模式",
    "runtime.mode_help.normal": "Normal：只读工具自动运行；编辑和命令需要授权。",
    "runtime.mode_help.accept-edits": "Accept Edits：读取和工作区编辑自动运行；命令及其他副作用仍需授权。",
    "runtime.mode_help.plan": "Plan：只允许只读探索；所有带副作用的请求都会被拒绝。",
    "runtime.mode_help.auto": "Auto（受限预览）：读取和编辑自动运行；安全分类器实现前，命令和网络操作仍需授权。",
    "runtime.mode_help_auto_unrestricted": "本次 Auto 由 --always-approve 显式授权。显式 deny 规则和进程沙箱仍然有效；安全分类器尚未实现。",
    "startup.resumed": "已恢复会话 {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "已就绪 · {provider}/{model} · {cwd}",
    "turn.running": "已有一轮任务正在运行。",
    "turn.waiting": "思考中……",
    "turn.no_response": "（没有文本回答）",
    "turn.cancelled": "本轮已取消。",
    "turn.reasoning": "正在推理……",
    "turn.thinking_completed": "思考完成 · {duration} · 第 {step} 个模型步骤",
    "turn.completed": "本轮完成 · 用时 {duration} · {steps} 个模型步骤",
    "turn.cancel_requested": "已请求取消。",
    "turn.draft_cleared": "草稿已清除。",
    "turn.none_running": "当前没有运行中的任务。",
    "provider.failed": "供应商 {provider} 在输出前失败：{message}",
    "provider.selected": "已选择供应商 {provider}/{model}。",
    "provider.fallback_selected": "已选择备用供应商 {provider}/{model}。",
    "tool.hosted_started": "● 托管工具 {name}",
    "tool.hosted_completed": "└ {name} 完成 · {duration}",
    "tool.requested": "● {invocation}",
    "tool.permission_allowed": "├ 已允许 · {policy}",
    "tool.permission_denied": "└ {name} 权限被拒绝：{reason}",
    "tool.awaiting_approval": "├ 等待授权 · {name}",
    "tool.approval_resolved": "├ 授权结果 {outcome} · {name}",
    "tool.completed": "└ {name} 完成 · {duration}",
    "tool.failed": "└ {name} 失败 · {duration}：{message}",
    "tool.card.hosted": "托管工具",
    "tool.card.allowed": "已允许 · {reason}",
    "tool.card.approval_required": "需要授权 · {reason}",
    "tool.card.awaiting_approval": "等待授权",
    "tool.card.approval": "授权结果 · {outcome}",
    "tool.card.running": "正在运行",
    "tool.card.output": "输出 · {lines} 行",
    "tool.card.output_empty": "输出 · 无输出",
    "tool.card.error": "错误输出 · {lines} 行",
    "tool.card.error_empty": "错误输出 · 无详细信息",
    "tool.card.lines_omitted": "……省略中间 {count} 行",
    "tool.card.preview_truncated": "……预览已达到显示上限",
    "tool.card.diff_truncated": "……差异已达到显示上限",
    "tool.card.details_expanded": "▾ 已展开详细信息 · 单击或按 Enter 收起",
    "tool.card.details_collapsed": "▸ 已收起详细信息 · 单击或按 Enter 展开",
    "tool.card.files_omitted": "……省略 {count} 个已变更文件",
    "tool.card.scan_limited": "工作区变更扫描已达到安全上限",
    "tool.card.change.created": "新建 {path}（+{additions}）",
    "tool.card.change.modified": "编辑 {path}（+{additions} -{deletions}）",
    "tool.card.change.deleted": "删除 {path}（-{deletions}）",
    "tool.card.hidden.sensitive": "敏感文件的变更内容已隐藏",
    "tool.card.hidden.large": "文件过大，变更内容已隐藏",
    "tool.card.hidden.budget": "扫描预算已用完，变更内容已隐藏",
    "tool.card.hidden.binary": "二进制变更，无法显示文本差异",
    "tool.card.hidden.redacted": "已变更的凭据值已脱敏",
    "tool.card.hidden.unavailable": "无法显示变更内容",
    "tool.card.completed": "完成 · {duration}",
    "tool.card.failed": "失败 · {duration}",
    "tool.card.denied": "已拒绝 · {reason}",
    "tool.approval.allow_once": "仅本次允许",
    "tool.approval.allow_session": "本会话允许",
    "tool.approval.deny": "已拒绝",
    "tool.approval.unknown": "已处理",
    "value.unknown": "未知",
    "command_hint.tab": "Tab 补全",
    "command.tasks_arguments": "/tasks 不接受参数。",
    "command.arguments": "/{command} 不接受参数。",
    "command.help": "命令：/help、/status、/mode [模式]、/settings（别名 /setting）、/provider [配置]（别名 /model）、/effort [等级]（别名 /reasoning）、/sessions [查询词]、/resume [会话 ID]、/rename 标题（别名 /title）、/tasks、/cancel、/clear、/quit（别名 /exit）。",
    "command.status": "供应商：{provider}/{model} · 上下文：{context} · 强度：{effort} · 模式：{mode} · 会话：{session}{profile} · 工作目录：{cwd}",
    "command.not_created": "尚未创建",
    "command.profile": " · 配置：{profile}",
    "command.unknown": "未知命令：/{command}。请使用 /help。",
    "transcript.cleared": "对话记录已清除。",
    "provider.switch_unavailable": "当前无法切换供应商。",
    "provider.switch_running": "任务运行期间不能切换供应商。",
    "effort.unavailable": "当前无法控制思考强度。",
    "effort.switch_running": "任务运行期间不能切换思考强度。",
    "effort.invalid": "未知强度 {value!r}。可选值：{levels}。",
    "effort.already_selected": "思考强度已经是 {glyph} {effort}。",
    "effort.changed": "思考强度已切换为 {glyph} {effort}；从下一次模型步骤开始生效。",
    "effort.changed_fallback": "已选择 Ultracode；工作流编排尚未实现，因此当前仅应用 {effective} 审查策略，不会启动子代理工作流。",
    "effort.save_failed": "本次运行的强度已切换，但无法保存该偏好：{error}",
    "mode.current": "当前模式：{mode}。可选模式：{modes}。",
    "mode.invalid": "未知模式 {value!r}。可选值：{modes}。",
    "mode.unavailable": "当前无法控制交互模式。",
    "mode.switch_running": "任务运行期间不能切换模式。",
    "mode.already_selected": "交互模式已经是 {glyph} {mode}。",
    "mode.changed": "交互模式已切换为 {glyph} {mode}。",
    "mode.changed_auto_limited": "已选择 Auto 安全预览：读取和编辑自动运行，命令及网络操作仍需授权；安全分类器尚未实现。",
    "mode.save_failed": "本次运行的模式已切换，但无法保存该偏好：{error}",
    "mode.limited": "受限",
    "provider.already_selected": "供应商配置 {profile} 已经处于选中状态。",
    "provider.switched": "供应商配置已切换到 {profile}（{provider}/{model}）。{stopped}",
    "provider.switched_saved": "供应商配置已切换到 {profile}（{provider}/{model}）。之前的会话 {session_id} 仍已保存；下一条提示将开始新对话。{stopped}",
    "tasks.stopped_one": " 已停止上一会话中的 1 个后台任务。",
    "tasks.stopped_many": " 已停止上一会话中的 {count} 个后台任务。",
    "session.resume_unavailable": "当前无法交互式恢复会话。",
    "session.resume_running": "任务运行期间不能恢复其他会话。",
    "session.none": "当前工作区没有会话。",
    "session.none_matching": "当前工作区没有匹配 {query!r} 的会话。",
    "session.rename_unavailable": "当前无法交互式重命名会话。",
    "session.rename_running": "任务运行期间不能重命名会话。",
    "session.renamed": "会话 {session_id} 已重命名为 {title!r}。",
    "session.already_open": "会话 {session_id} 已经打开。",
    "session.profile": "配置 {profile}",
    "session.profile_unavailable": "配置 {profile}；源配置 {source} 尚未在本地就绪",
    "session.previous_saved": " 之前的会话 {session_id} 仍已保存。",
    "session.resumed": "已恢复会话 {session_id}，使用{profile_note}（{provider}/{model}）。{previous}{stopped}",
    "tasks.unavailable": "当前无法查看后台任务。",
    "tasks.none": "当前会话没有后台任务。",
    "tasks.heading": "后台任务：\n{lines}",
    "tasks.omitted": "……已省略 {count} 个较早任务",
    "tasks.summary": "{task_id} · {status}{exit_note} · 输出 {bytes} 字节{truncated} · 开始于 {started}",
    "tasks.exit": " · 退出码 {code}",
    "tasks.truncated": "（预览已截断）",
    "tasks.status.running": "运行中",
    "tasks.status.completed": "已完成",
    "tasks.status.failed": "失败",
    "tasks.status.timed_out": "已超时",
    "tasks.status.cancelled": "已取消",
    "tasks.completion.completed": "后台任务 {task_id} 已完成{exit_note}。",
    "tasks.completion.failed": "后台任务 {task_id} 失败{exit_note}。",
    "tasks.completion.timed_out": "后台任务 {task_id} 已超时{exit_note}。",
    "tasks.completion.cancelled": "后台任务 {task_id} 已取消{exit_note}。",
    "tasks.completion.exit": "（退出码 {code}）",
    "restore.result": "已恢复工具 {name} 的结果。",
    "restore.request": "已恢复工具请求：{names}。",
    "restore.truncated": "……[恢复的消息已截断]",
    "settings.changed": "界面语言已切换为{language}。",
    "settings.save_failed": "本次会话的语言已切换，但无法保存该偏好：{error}",
}

if _ENGLISH.keys() != _CHINESE.keys():
    raise RuntimeError("TUI translation catalogs must contain identical keys")

_CATALOGS: Final[Mapping[UiLanguage, Mapping[str, str]]] = {
    UiLanguage.ENGLISH: _ENGLISH,
    UiLanguage.SIMPLIFIED_CHINESE: _CHINESE,
}


def ui_text(locale: UiLanguage, key: str, **values: object) -> str:
    """Render one owned UI string while leaving conversation content untouched."""

    template = _CATALOGS[locale][key]
    return template.format_map(values)


def language_name(language: UiLanguage, *, in_language: UiLanguage) -> str:
    names = {
        UiLanguage.ENGLISH: {
            UiLanguage.ENGLISH: "English",
            UiLanguage.SIMPLIFIED_CHINESE: "Simplified Chinese",
        },
        UiLanguage.SIMPLIFIED_CHINESE: {
            UiLanguage.ENGLISH: "英语",
            UiLanguage.SIMPLIFIED_CHINESE: "简体中文",
        },
    }
    return names[in_language][language]


__all__ = ["language_name", "ui_text"]
