# ruff: noqa: RUF001
from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from neuro_code.domain.ui_preferences import UiLanguage

# Natural Chinese interface copy deliberately uses full-width punctuation.

_ENGLISH: Final[dict[str, str]] = {
    "subtitle": "Terminal coding agent",
    "prompt.placeholder": "Ask Neuro Code... (/help for commands)",
    "shortcuts": "^C Cancel   ^Q Quit   ^P Provider   ^R Sessions   ^, Settings   ^L Clear",
    "label.error": "Error",
    "label.status": "Status",
    "label.tool": "Tool",
    "approval.title": "Tool approval required",
    "approval.tool": "Tool: {tool}",
    "approval.policy": "Policy: {policy}",
    "approval.allow_once": "Allow once [A]",
    "approval.allow_session": "Allow identical action this session [S]",
    "approval.unscoped": "Session approval is unavailable for an action that cannot be scoped safely.",
    "approval.deny": "Deny [D/Esc/Ctrl+C]",
    "provider.title": "Select provider profile",
    "provider.help": "Switching profile starts a new conversation. Esc/Ctrl+C closes this picker.",
    "marker.current": "current",
    "marker.default": "default",
    "marker.unavailable": "unavailable",
    "marker.credential_missing": "credential missing",
    "session.search": "Session search: {query}",
    "session.title": "Workspace sessions",
    "session.help": "Only sessions from this workspace are listed. Filter with /sessions QUERY. Esc/Ctrl+C closes this picker.",
    "session.resume_via": "resume via {profile}",
    "session.legacy_sandbox": "legacy sandbox",
    "session.sandbox": "sandbox {profile}",
    "session.restart_required": "restart required",
    "settings.title": "Settings",
    "settings.description": "Interface language",
    "settings.current": "current",
    "settings.help": "The choice applies immediately and is saved for future TUI launches.",
    "startup.resumed": "Resumed session {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "Ready · {provider}/{model} · {cwd}",
    "turn.running": "A turn is already running.",
    "turn.waiting": "Thinking...",
    "turn.no_response": "(no text response)",
    "turn.cancelled": "Turn cancelled.",
    "turn.reasoning": "Reasoning...",
    "turn.cancel_requested": "Cancellation requested.",
    "turn.draft_cleared": "Draft cleared.",
    "turn.none_running": "No turn is running.",
    "provider.failed": "Provider {provider} failed before output: {message}",
    "provider.selected": "Provider {provider}/{model} selected.",
    "provider.fallback_selected": "Provider {provider}/{model} fallback selected.",
    "tool.hosted_started": "Hosted tool {name} started.",
    "tool.hosted_completed": "Hosted tool {name} completed.",
    "tool.requested": "Tool {name} requested.",
    "tool.permission_denied": "Tool {name} permission: {effect} ({reason}).",
    "tool.awaiting_approval": "Tool {name} is waiting for approval.",
    "tool.approval_resolved": "Tool {name} approval resolved: {outcome}.",
    "tool.completed": "Tool {name} completed.",
    "tool.failed": "Tool {name} failed.",
    "value.unknown": "unknown",
    "command.tasks_arguments": "/tasks does not accept arguments.",
    "command.arguments": "/{command} does not accept arguments.",
    "command.help": "Commands: /help, /status, /settings (alias /setting), /provider [PROFILE] (alias /model), /sessions [QUERY], /resume [SESSION_ID], /rename TITLE (alias /title), /tasks, /cancel, /clear, /quit (alias /exit).",
    "command.status": "Provider: {provider}/{model} · Session: {session}{profile} · CWD: {cwd}",
    "command.not_created": "not created",
    "command.profile": " · Profile: {profile}",
    "command.unknown": "Unknown command: /{command}. Use /help.",
    "transcript.cleared": "Transcript cleared.",
    "provider.switch_unavailable": "Provider switching is unavailable.",
    "provider.switch_running": "Cannot switch provider while a turn is running.",
    "provider.already_selected": "Provider profile {profile} is already selected.",
    "provider.switched": "Provider profile switched to {profile} ({provider}/{model}).{stopped}",
    "provider.switched_saved": "Provider profile switched to {profile} ({provider}/{model}). The previous session {session_id} remains saved; the next prompt starts a new conversation.{stopped}",
    "tasks.stopped_one": " Stopped 1 background task from the previous session.",
    "tasks.stopped_many": " Stopped {count} background tasks from the previous session.",
    "session.resume_unavailable": "Interactive session resume is unavailable.",
    "session.resume_running": "Cannot resume a session while a turn is running.",
    "session.none": "No sessions found for this workspace.",
    "session.none_matching": "No sessions found for this workspace matching {query!r}.",
    "session.rename_unavailable": "Interactive session rename is unavailable.",
    "session.rename_running": "Cannot rename a session while a turn is running.",
    "session.renamed": "Session {session_id} renamed to {title!r}.",
    "session.already_open": "Session {session_id} is already open.",
    "session.profile": "profile {profile}",
    "session.profile_unavailable": "profile {profile}; source profile {source} is not ready locally",
    "session.previous_saved": " Previous session {session_id} remains saved.",
    "session.resumed": "Resumed session {session_id} with {profile_note} ({provider}/{model}).{previous}{stopped}",
    "tasks.unavailable": "Background task visibility is unavailable.",
    "tasks.none": "No background tasks for the current session.",
    "tasks.heading": "Background tasks:\n{lines}",
    "tasks.omitted": "... {count} older task(s) omitted",
    "tasks.summary": "{task_id} · {status}{exit_note} · {bytes} output bytes{truncated} · started {started}",
    "tasks.exit": " · exit {code}",
    "tasks.truncated": " (preview truncated)",
    "tasks.status.running": "running",
    "tasks.status.completed": "completed",
    "tasks.status.failed": "failed",
    "tasks.status.timed_out": "timed out",
    "tasks.status.cancelled": "cancelled",
    "tasks.completion.completed": "Background task {task_id} completed{exit_note}.",
    "tasks.completion.failed": "Background task {task_id} failed{exit_note}.",
    "tasks.completion.timed_out": "Background task {task_id} timed out{exit_note}.",
    "tasks.completion.cancelled": "Background task {task_id} was cancelled{exit_note}.",
    "tasks.completion.exit": " (exit {code})",
    "restore.result": "Restored result for {name}.",
    "restore.request": "Restored tool request: {names}.",
    "restore.truncated": "... [restored message truncated]",
    "settings.changed": "Interface language changed to {language}.",
    "settings.save_failed": "The language changed for this session, but the preference could not be saved: {error}",
}

_CHINESE: Final[dict[str, str]] = {
    "subtitle": "终端编程智能体",
    "prompt.placeholder": "询问 Neuro Code……（输入 /help 查看命令）",
    "shortcuts": "^C 取消   ^Q 退出   ^P 供应商   ^R 会话   ^, 设置   ^L 清屏",
    "label.error": "错误",
    "label.status": "状态",
    "label.tool": "工具",
    "approval.title": "需要工具授权",
    "approval.tool": "工具：{tool}",
    "approval.policy": "策略：{policy}",
    "approval.allow_once": "仅允许本次 [A]",
    "approval.allow_session": "本会话允许相同操作 [S]",
    "approval.unscoped": "该操作无法安全限定范围，因此不能授予会话级权限。",
    "approval.deny": "拒绝 [D/Esc/Ctrl+C]",
    "provider.title": "选择供应商配置",
    "provider.help": "切换配置会开始新对话。按 Esc/Ctrl+C 关闭选择器。",
    "marker.current": "当前",
    "marker.default": "默认",
    "marker.unavailable": "不可用",
    "marker.credential_missing": "缺少凭据",
    "session.search": "会话搜索：{query}",
    "session.title": "当前工作区会话",
    "session.help": "仅列出当前工作区的会话。使用 /sessions 查询词筛选；按 Esc/Ctrl+C 关闭。",
    "session.resume_via": "通过 {profile} 恢复",
    "session.legacy_sandbox": "旧版沙箱",
    "session.sandbox": "沙箱 {profile}",
    "session.restart_required": "需要重启",
    "settings.title": "设置",
    "settings.description": "界面语言",
    "settings.current": "当前",
    "settings.help": "选择会立即生效，并用于以后启动的 TUI。",
    "startup.resumed": "已恢复会话 {session_id} · {provider}/{model} · {cwd}",
    "startup.ready": "已就绪 · {provider}/{model} · {cwd}",
    "turn.running": "已有一轮任务正在运行。",
    "turn.waiting": "思考中……",
    "turn.no_response": "（没有文本回答）",
    "turn.cancelled": "本轮已取消。",
    "turn.reasoning": "正在推理……",
    "turn.cancel_requested": "已请求取消。",
    "turn.draft_cleared": "草稿已清除。",
    "turn.none_running": "当前没有运行中的任务。",
    "provider.failed": "供应商 {provider} 在输出前失败：{message}",
    "provider.selected": "已选择供应商 {provider}/{model}。",
    "provider.fallback_selected": "已选择备用供应商 {provider}/{model}。",
    "tool.hosted_started": "托管工具 {name} 已启动。",
    "tool.hosted_completed": "托管工具 {name} 已完成。",
    "tool.requested": "已请求工具 {name}。",
    "tool.permission_denied": "工具 {name} 权限：{effect}（{reason}）。",
    "tool.awaiting_approval": "工具 {name} 正在等待授权。",
    "tool.approval_resolved": "工具 {name} 授权结果：{outcome}。",
    "tool.completed": "工具 {name} 已完成。",
    "tool.failed": "工具 {name} 执行失败。",
    "value.unknown": "未知",
    "command.tasks_arguments": "/tasks 不接受参数。",
    "command.arguments": "/{command} 不接受参数。",
    "command.help": "命令：/help、/status、/settings（别名 /setting）、/provider [配置]（别名 /model）、/sessions [查询词]、/resume [会话 ID]、/rename 标题（别名 /title）、/tasks、/cancel、/clear、/quit（别名 /exit）。",
    "command.status": "供应商：{provider}/{model} · 会话：{session}{profile} · 工作目录：{cwd}",
    "command.not_created": "尚未创建",
    "command.profile": " · 配置：{profile}",
    "command.unknown": "未知命令：/{command}。请使用 /help。",
    "transcript.cleared": "对话记录已清除。",
    "provider.switch_unavailable": "当前无法切换供应商。",
    "provider.switch_running": "任务运行期间不能切换供应商。",
    "provider.already_selected": "供应商配置 {profile} 已经处于选中状态。",
    "provider.switched": "供应商配置已切换到 {profile}（{provider}/{model}）。{stopped}",
    "provider.switched_saved": "供应商配置已切换到 {profile}（{provider}/{model}）。之前的会话 {session_id} 仍已保存；下一条提示将开始新对话。{stopped}",
    "tasks.stopped_one": " 已停止上一会话中的 1 个后台任务。",
    "tasks.stopped_many": " 已停止上一会话中的 {count} 个后台任务。",
    "session.resume_unavailable": "当前无法交互式恢复会话。",
    "session.resume_running": "任务运行期间不能恢复其他会话。",
    "session.none": "当前工作区没有会话。",
    "session.none_matching": "当前工作区没有匹配 {query!r} 的会话。",
    "session.rename_unavailable": "当前无法交互式重命名会话。",
    "session.rename_running": "任务运行期间不能重命名会话。",
    "session.renamed": "会话 {session_id} 已重命名为 {title!r}。",
    "session.already_open": "会话 {session_id} 已经打开。",
    "session.profile": "配置 {profile}",
    "session.profile_unavailable": "配置 {profile}；源配置 {source} 尚未在本地就绪",
    "session.previous_saved": " 之前的会话 {session_id} 仍已保存。",
    "session.resumed": "已恢复会话 {session_id}，使用{profile_note}（{provider}/{model}）。{previous}{stopped}",
    "tasks.unavailable": "当前无法查看后台任务。",
    "tasks.none": "当前会话没有后台任务。",
    "tasks.heading": "后台任务：\n{lines}",
    "tasks.omitted": "……已省略 {count} 个较早任务",
    "tasks.summary": "{task_id} · {status}{exit_note} · 输出 {bytes} 字节{truncated} · 开始于 {started}",
    "tasks.exit": " · 退出码 {code}",
    "tasks.truncated": "（预览已截断）",
    "tasks.status.running": "运行中",
    "tasks.status.completed": "已完成",
    "tasks.status.failed": "失败",
    "tasks.status.timed_out": "已超时",
    "tasks.status.cancelled": "已取消",
    "tasks.completion.completed": "后台任务 {task_id} 已完成{exit_note}。",
    "tasks.completion.failed": "后台任务 {task_id} 失败{exit_note}。",
    "tasks.completion.timed_out": "后台任务 {task_id} 已超时{exit_note}。",
    "tasks.completion.cancelled": "后台任务 {task_id} 已取消{exit_note}。",
    "tasks.completion.exit": "（退出码 {code}）",
    "restore.result": "已恢复工具 {name} 的结果。",
    "restore.request": "已恢复工具请求：{names}。",
    "restore.truncated": "……[恢复的消息已截断]",
    "settings.changed": "界面语言已切换为{language}。",
    "settings.save_failed": "本次会话的语言已切换，但无法保存该偏好：{error}",
}

if _ENGLISH.keys() != _CHINESE.keys():
    raise RuntimeError("TUI translation catalogs must contain identical keys")

_CATALOGS: Final[Mapping[UiLanguage, Mapping[str, str]]] = {
    UiLanguage.ENGLISH: _ENGLISH,
    UiLanguage.SIMPLIFIED_CHINESE: _CHINESE,
}


def ui_text(locale: UiLanguage, key: str, **values: object) -> str:
    """Render one owned UI string while leaving conversation content untouched."""

    template = _CATALOGS[locale][key]
    return template.format_map(values)


def language_name(language: UiLanguage, *, in_language: UiLanguage) -> str:
    names = {
        UiLanguage.ENGLISH: {
            UiLanguage.ENGLISH: "English",
            UiLanguage.SIMPLIFIED_CHINESE: "Simplified Chinese",
        },
        UiLanguage.SIMPLIFIED_CHINESE: {
            UiLanguage.ENGLISH: "英语",
            UiLanguage.SIMPLIFIED_CHINESE: "简体中文",
        },
    }
    return names[in_language][language]


__all__ = ["language_name", "ui_text"]
